//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poker
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSession
    {
        public int id { get; set; }
        public Nullable<int> p1score { get; set; }
        public Nullable<int> p2score { get; set; }
        public string p1hand { get; set; }
        public string p2hand { get; set; }
        public string p1remaining { get; set; }
        public string p2remaining { get; set; }
        public Nullable<int> p1played { get; set; }
        public Nullable<int> p2played { get; set; }
        public Nullable<int> first_player { get; set; }
        public Nullable<int> on_player { get; set; }
        public Nullable<int> stick_round { get; set; }
        public Nullable<int> sub_round { get; set; }
    }
}
